### ISSUE TITLE
Please update to 1.0.3 (change 2 lines in formula. Compiled for me on osx 10.10 & 10.11)

### ISSUE THREAD

**Issue by dukechem** [samangh/gptfdisk#2]
I could fork if you want ;-)    but I think you can make your formula compile 1.0.3 by changing 2 lines:

`  url "https://newcontinuum.dl.sourceforge.net/project/gptfdisk/gptfdisk/1.0.3/gptfdisk-1.0.3.tar.gz"
  sha256 "89fd5aec35c409d610a36cb49c65b442058565ed84042f767bba614b8fc91b5c"
`
The ncurses patch in formula still seems to work ok, tho I did not test thorougly so cavaet emptor.
Compiles and runs ok for me on 10.10 and 10.11 osx. Drops man pages in place nicely, too!
`/usr/local/sbin/gdisk -V
GPT fdisk (gdisk) version 1.0.3
`

**Comment by samangh** [comment]
Thanks for lettimg me know about the new version 👍 . The formula has been update to get 1.0.3 from upstream :-)

Fixed in https://github.com/samangh/homebrew-tap/commit/9b871b79ee831a780cfbd256c8afb37d784b3eb2.
