### ISSUE TITLE
Additional releases required for Windows operating system.

### ISSUE THREAD

**Issue by BoQsc** [samangh/gptfdisk#3]
I'm aware of sourceforge and have no clue of how to compile gdisk for Windows.
I'm asking for at least one release of Windows to be uploaded directly on github, for easier access and additional preservation, the future.

https://github.com/samangh/gptfdisk/releases

**Comment by samangh** [comment]
No problem, done.

https://github.com/samangh/gptfdisk/releases/tag/v1.0.4
