### ISSUE TITLE
Partitions on USB Flash device with an Attribute: Hidden (62) are still visable in Windows 10

### ISSUE THREAD

**Issue by BoQsc** [samangh/gptfdisk#4]
This seems to not work anymore, if it ever worked for Windows operating systems:
https://brashear.me/blog/2017/10/26/hide-a-partition-from-windows-using-linux/

### Setting attribute  
> 1. Open the disk with `gdisk :1`
> 2. List partitions with `p`
> 3. Enter expert mode with `x`
> 4. Use `a` to set attributes.
> 5. Enter the partition number. gdisk will show what the current fields are and a list of known attributes.
> 6. Type `62` and hit enter to set the hidden attribute. Hit enter again if you’re done setting attributes.
> 7. Use `w` to write the partition table.

Boot up into Windows (if you aren't already) and see that the partition is mounted and not hidden.

Btw. I have 3 partitions on my own testing USB flash device. Haven't tried to hide a single partition inside single partition flash drive.

**Comment by samangh** [comment]
Please report this issue to upstream at https://sourceforge.net/projects/gptfdisk/.

This repository is a mirror.

**Comment by BoQsc** [comment]
@samangh Did you mean https://sourceforge.net/p/gptfdisk/discussion/
